export const appThemetoggleElement = document.querySelector('.app__theme-toggle');
export const appThemetoggleElementImage = document.querySelector('.app__theme-toggle--img');
export const bodyElement = document.querySelector('body');
export const addTaskButton = document.querySelector('.app__search-bar__button');
export const inputElement = document.querySelector('.app__search-bar__input');
export const taskListElement = document.querySelector('.app__task-list__list');
export const itemsLeftElement = document.querySelector('.items--number');
export const allButtonElement = document.querySelector('.all-button');
export const activeButtonElement = document.querySelector('.active-button');
export const completedButtonElement = document.querySelector('.complete-button');
export const clearButtonElement = document.querySelector('.clear-button');
export const getDeleteElements = () => document.querySelectorAll('.remove');
export const getListItemElements = () => document.querySelectorAll('.list-item');
export const getCurrentListElements = () => document.querySelectorAll('.draggable');
